# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='activated',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='socialnetwork',
            name='activated',
            field=models.BooleanField(default=1),
        ),
    ]
